FROM drezael/ubuntu:20.04
RUN dpkg --add-architecture i386
RUN apt update && apt upgrade -y
RUN apt install -y -q gcc-10-base:i386 libc6:i386 libcrypt1:i386 libgcc-s1:i386 libidn2-0:i386 libstdc++6:i386 \
libunistring2:i386 glibc-doc:i386 steam:i386 musl libc6 libc-bin libsdl2-2.0-0:i386 libsdl2-2.0-0 libsdl2-dev \
libsdl2-image-2.0-0 libsdl2-mixer-2.0-0 libsdl2-net-2.0-0 libsdl2-ttf-2.0-0
COPY ./apps/steamcmd/ /tmp/steamcmd
RUN cp -r /tmp/steamcmd/* / && rm -r /tmp/steamcmd
RUN /usr/games/steamcmd +exit
RUN echo "Image crated -> $(date +%s)" > /root/creation_times/"creation_drezael_steamcmd:ubuntu_20.04"